### PR TITLE
Automating compilation with Docker

### PR DESCRIPTION
**Pull request by arthurd2**

### CODE REVIEW

**Comment by bollinim** [comment]
Does the resulting tgz package is being unarchived correctly? This is the unarchive error i got in Botpress and Unzip utilities.
> Error while loading some modules, they will be disabled [ZlibError, zlib: unexpected end of file]

**Comment by bollinim** [comment]
Thank you!

**Comment by arthurd2** [comment]
Hi Michele, 
Yes I'm having the same problem but I guess is due another issue.
 **Build** is ok:
```
[16:38:22] Starting 'build-module channel-rocketchat'...
[16:38:37] Finished 'build-module channel-rocketchat' after 15 s
```
**Packing** is generating a small issue:
```
[module-builder] Writing to "/bp/out/binaries/modules/channel-rocketchat.tgz"
[module-builder] Zipping 407 files...
[module-builder] Error packaging module: ELOOP: too many symbolic links encountered, stat '/bp/modules/channel-rocketchat/node_production_modules/asteroid/test/dist'  
[module-builder] Cleaning up temporary files...

[16:49:54] Finished 'package-module channel-rocketchat' after 8.42 s
[16:49:54] Starting 'package-module channel-slack'...
[module-builder] Installing production modules...
[module-builder] yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
Done in 16.92s.
```

**Comment by arthurd2** [comment]
I will open an issue... ;)

**Comment by arthurd2** [comment]
If you want, you can assign the issue to me...

**Pull request merged**
